/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gtnewhorizons.gtnhgradle;

import com.google.common.collect.ImmutableMap;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'com.gtnewhorizons.gtnhgradle.greeting' plugin.
 */
class GTNHGradlePluginTest {

    private static final ImmutableMap<String, String> SIMPLE_PROPERTIES = ImmutableMap.of(
        "modName",
        "MyMod",
        "modId",
        "mymodid",
        "modGroup",
        "com.myname.mymodid",
        "enableModernJavaSyntax",
        "true",
        "enableGenericInjection",
        "true");

    private static Project makeGtnhProject() {
        final Project project = ProjectBuilder.builder()
            .build();
        // Set some required properties
        for (var entry : SIMPLE_PROPERTIES.entrySet()) {
            project.getExtensions()
                .getExtraProperties()
                .set(entry.getKey(), entry.getValue());
        }
        project.getPlugins()
            .apply("com.gtnewhorizons.gtnhgradle");
        return project;
    }

    @Test
    void pluginRegistersATask() {
        final Project project = makeGtnhProject();

        assertNotNull(
            project.getTasks()
                .findByName("downloadVanillaJars")); // Check RFG tasks
    }

    @Test
    void gtnhExtensionAccessible() {
        final Project project = makeGtnhProject();
        assertInstanceOf(
            GTNHGradlePlugin.GTNHExtension.class,
            project.getExtensions()
                .getByName("gtnhGradle"));
    }
}
