
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up JDK versions
      uses: actions/setup-java@v5
      with:
        java-version: |
          21
          8
          17
        distribution: 'zulu'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        validate-wrappers: true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build the Gradle plugin
      run: ./gradlew --build-cache --info --stacktrace assemble

    - name: Test the plugin
      run: ./gradlew --build-cache --info --stacktrace check
